import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.page.html',
  styleUrls: ['./search.page.scss'],
})
export class SearchPage implements OnInit {

  lista!: string[];
  listaFiltrada!: string[];

  constructor() { 
    this.inicializar();
    this.listaFiltrada = [...this.lista];
  }

  ngOnInit() {
  }

  inicializar(){
    this.lista = [
    'EL VALLECITO',
    'SIERRA DE SAN FRANCISCO',
    'BALAMKÚ',
    'BECÁN',
    'CALAKMUL',
    'CHUNHUHUB',
    'CHICANNÁ',
    'DZIBILNOCAC',
    'EDZNÁ',
    'EL TIGRE',
    'HOCHOB',
    'EL HORMIGUERO',
    'KANKÍ',
    'SANTA MARÍA XTAMPAK',
    'TABASQUEÑO',
    'TOHCOK',
    'XCALUMKÍN',
    'XPUHIL',
    'BONAMPAK',
    'CHIAPA DE CORZO',
    'CHINKULTIC',
    'IGLESIA VIEJA',
    'IZAPA',
    'LAGARTERO',
    'TENAM PUENTE',
    'PALENQUE',
    'TONINÁ',
    'YAXCHILÁN',
    'CUARENTA CASAS',
    'CUEVA GRANDE',
    'CUEVA DE LA OLLA',
    'HUAPOCA',
    'PAQUIMÉ',
    'CUICUILCO',
    'TEMPLO MAYOR',
    'MIXCOAC',
    'TLATELOLCO',
    'CERRO DE LA ESTRELLA',
    'Zona Paleontológica Rincón colorado',
    'EL CHANAL',
    'LA CAMPANA',
    'LA FERRERÍA',
    'IXTAPALUCA',
    'CALIXTLAHUACA',
    'CHIMALHUACAN',
    'EL CONDE',
    'HUAMANGO',
    'HUEXOTLA',
    'LOS MELONES',
    'LOS REYES LA PAZ',
    'MALINALCO',
    'SAN MIGUEL IXTAPAN',
    'TENAYUCA l Y ll',
    'TEOTENANGO',
    'TEOTIHUACAN',
    'TETZCOTZINGO',
    'TLAPACOYA',
    'TOCUILA',
    'SANTA CECILA ACATITLÁN',
    'OCOYOACAC',
    'ARROYO SECO',
    'CAÑADA DE LA VIRGEN',
    'EL CÓPORO',
    'PERALTA',
    'PLAZUELAS',
    'QUERENDE',
    'SOLEDAD DE MACIEL',
    'HUAMUXTITLÁN',
    'IXCATEOPAN',
    'XOCHIPALA',
    'LA SABANA',
    'LOS TEPOLTZIS',
    'PALMA SOLA',
    'TEHUACALCO',
    'TEOPANTECUANITLAN',
    'HUAPALCALCO',
    'PAÑHU',
    'TULA',
    'TEPEAPULCO',
    'IXTÉPETE',
    'GUACHIMONTONES',
    'SAN FELIPE LOS ALZATI',
    'HUANDACAREO LA NOPALERA',
    'TRES CERRITOS',
    'TZINTZUNTZAN',
    'IHUATZIO',
    'TINGAMBATO',
    'OLINTEPEC',
    'CHALCATZINGO',
    'COATETELCO',
    'LAS PILAS',
    'TEOPANZOLCO',
    'TEPOZTECO',
    'XOCHICALCO',
    'YAUTEPEC',
    'IXTLÁN DEL RÍO',
    'BOCA DE POTRERILLOS',
    'ATZOMPA',
    'BOCANA DEL RÍO COPALITA',
    'DAINZÚ',
    'GUIENGOLA',
    'HUAMELUPAN',
    'LAMBITYECO',
    'MITLA',
    'MONTE ALBÁN',
    'YAGUL',
    'ZAACHILA',
    'TEPAPAYECA',
    'CANTONA',
    'CHOLULA',
    'CERRITOS DE SAN CRISTÓBAL',
    'TEPEXI EL VIEJO',
    'YOHUALINCHAN',
    'EL CERRITO',
    'LAS RANAS',
    'TANCAMA',
    'TOLUQUILLA',
    'CALICA',
    'CHANKANBAKAN',
    'COBÁ',
    'CARACOL',
    'CHACHOBEN',
    'DZIBANCHÉ',
    'KINICHNÁ',
    'EL MECO',
    'EL REY',
    'KOHUNLICH',
    'MUYIL',
    'OXTANKAH',
    'PLAYA DEL CARMEN',
    'SAN GERVASIO',
    'SAN MIGUELTO',
    'TULUM',
    'XELHÁ',
    'XCARET',
    'TAMOHI',
    'TAMTOC',
    'LAS LABRADAS',
    'CERRO DE LAS TRINCHERAS',
    'COMALCALCO',
    'LA VENTA',
    'MALPASITO',
    'MORAL - REFORMA',
    'POMONÁ',
    'BALCÓN DE MOCTEZUMA',
    'EL SABINITO',
    'LAS FLORES',
    'CACAXTLA',
    'OCOTELULCO',
    'TIZATLÁN',
    'TECOAQUE',
    'CASTILLO DE TEAYO',
    'CEMPOALA',
    'CUAJILOTE',
    'CUYUXQUIHUI',
    'EL TAJÍN',
    'LAS HIGUERAS',
    'QUIANHUIZTLÁN',
    'SAN LORENZO TENOCHTITLAN',
    'TRES ZAPOTES',
    'VEGA DE LA PEÑA',
    'ACANCEH',
    'AKÉ',
    'BALAMCANCHÉ',
    'CHACMULTÚN',
    'CHICHÉN ITZÁ',
    'DZIBILCHALTÚN',
    'EK BALAM',
    'IZAMAL',
    'KABAH',
    'LABNÁ',
    'LOLTÚN',
    'MAYAPÁN',
    'OXKINTOK',
    'SAYIL',
    'XLAPAK',
    'XCAMBÓ',
    'UXMAL',
    'ALTA VISTA CHALCHIHUITES',
    'CERRO DE LAS VENTANAS',
    'LA QUEMADA',
    ]
  }

  buscar(ev: any) {
    const val = ev.target.value.toLowerCase();

    if (val && val.trim() !== '') {
      this.listaFiltrada = this.lista.filter((item) => {
        return item.toLowerCase().includes(val);
      });
    } else {
      this.listaFiltrada = [...this.lista];
    }
  }

}
